name: Build and Test

on:
  pull_request:
    branches: [ main ]

jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    container:
      image: stronglytyped/arm-none-eabi-gcc:latest
    timeout-minutes: 5
    steps:
      - name: checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: print toolchain version
        run:  arm-none-eabi-gcc --version
      - name: build project
        run:  make build
      - name: upload build files
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: BuildFiles
          retention-days: 1
          path: |
            nucleo-f446re/ButtonLed/build/ButtonLed.elf
            nucleo-f446re/ButtonLed/build/ButtonLed.hex
  run-tests:
    name: Run Robot tests
    needs: build-project
    runs-on: ubuntu-latest
    container:
      image: antmicro/renode:latest
      options: --user root
    timeout-minutes: 5
    steps:
      - name: checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: print renode version
        run:  renode --version
      - name: download build files
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: BuildFiles
          path: nucleo-f446re/ButtonLed/build
      - name: run tests
        run:  make test
      - name: upload results
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: TestResults
          retention-days: 1
          path: |
            log.html
            report.html
